export const CATALOG_ROUTE = '/catalog'
export const DELIVERY_ROUTE = '/delivery'
export const CONTACT_ROUTE = '/contact'
export const ABOUT_ROUTE = '/about'
export const HOME_ROUTE = '/'
export const NEWS_ROUTE = '/news'
export const DEVICE_ROUTE = '/device'
export const PRODUCT_ROUTE = '/product/:id'
export const CART_ROUTE = '/cart'
export const CHECKOUT_ROUTE = '/checkout'
export const WISHLIST_ROUTE = '/wishlist'
export const LOGIN_ROUTE = '/login'
export const ERROR_ROUTE = '/error'
export const SINGLE_ROUTE = '/single/:id'
export const MYACOUNT_ROUTE = '/my-acount'
export const SUBCATEGORY_ROUTE = '/subcategory'
export const PURCHASES_ROUTE = '/purchases'
export const FORGET_ROUTE = '/forget'
export const QUICKVIEW_ROUTE = '/quickview'
export const CHANGEPASS_ROUTE = '/api/password_reset/validate_token/:token'
export const VISA_ROUTE = '/visa'


export const ORDER_ROUTE = '/orders'

